-- Your SQL goes here
ALTER TABLE users DROP CONSTRAINT users_pkey;
ALTER TABLE users DROP COLUMN id;
ALTER TABLE users ADD COLUMN id TEXT NOT NULL;
ALTER TABLE users ADD COLUMN idx SERIAL PRIMARY KEY;
